generate:
	- proteus -p /Users/joaoribeiro/workspace/go/personal/src/go-learn/60_grpc/example_5/generator/models -f /Users/joaoribeiro/workspace/go/personal/src/go-learn/60_grpc/example_5/generator/proto --verbose
	- proteus -p /Users/joaoribeiro/workspace/go/personal/src/go-learn/60_grpc/example_5/generator/models -f /Users/joaoribeiro/workspace/go/personal/src/go-learn/60_grpc/example_5/generator/proto --verbose
